USE [master]
GO
/****** Object:  Database [DB_WebACC]    Script Date: 07/11/2023 10:15:50 CH ******/
CREATE DATABASE [DB_WebACC]
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_WebACC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DB_WebACC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DB_WebACC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DB_WebACC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DB_WebACC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DB_WebACC] SET ARITHABORT OFF 
GO
ALTER DATABASE [DB_WebACC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DB_WebACC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DB_WebACC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DB_WebACC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DB_WebACC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DB_WebACC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DB_WebACC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DB_WebACC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DB_WebACC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DB_WebACC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DB_WebACC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DB_WebACC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DB_WebACC] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DB_WebACC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DB_WebACC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DB_WebACC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DB_WebACC] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DB_WebACC] SET RECOVERY FULL 
GO
ALTER DATABASE [DB_WebACC] SET  MULTI_USER 
GO
ALTER DATABASE [DB_WebACC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DB_WebACC] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DB_WebACC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DB_WebACC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DB_WebACC] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DB_WebACC] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DB_WebACC', N'ON'
GO
ALTER DATABASE [DB_WebACC] SET QUERY_STORE = ON
GO
ALTER DATABASE [DB_WebACC] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [DB_WebACC]
GO
/****** Object:  Table [dbo].[AdminMenu]    Script Date: 07/11/2023 10:15:50 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AdminMenu](
	[AdminMenuID] [bigint] NOT NULL,
	[ItemName] [nvarchar](50) NULL,
	[ItemLevel] [int] NULL,
	[ParentLevel] [int] NULL,
	[ItemOrder] [int] NULL,
	[IsActive] [bit] NULL,
	[ItemTarget] [nvarchar](50) NULL,
	[AreaName] [nvarchar](50) NULL,
	[ControllerName] [nvarchar](50) NULL,
	[ActionName] [nvarchar](50) NULL,
	[Icon] [nvarchar](50) NULL,
	[IdName] [nvarchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GI]    Script Date: 07/11/2023 10:15:50 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GI](
	[UID] [int] NULL,
	[LV] [int] NULL,
	[CharCount] [int] NULL,
	[Weapon] [int] NULL,
	[Server] [char](10) NULL,
	[Type] [char](10) NULL,
	[UserName] [char](30) NULL,
	[Password] [char](30) NULL,
	[Sold] [bit] NULL,
	[Img] [char](256) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HI]    Script Date: 07/11/2023 10:15:50 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HI](
	[UID] [int] NOT NULL,
	[LV] [int] NULL,
	[CharCount] [int] NULL,
	[Weapon] [int] NULL,
	[Server] [char](10) NULL,
	[Type] [char](10) NULL,
	[UserName] [char](30) NULL,
	[Password] [char](30) NULL,
	[Sold] [bit] NULL,
	[Img] [char](256) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HSR]    Script Date: 07/11/2023 10:15:50 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HSR](
	[UID] [int] NULL,
	[LV] [int] NULL,
	[CharCount] [int] NULL,
	[Weapon] [int] NULL,
	[Server] [char](10) NULL,
	[Type] [char](10) NULL,
	[UserName] [char](30) NULL,
	[Password] [char](30) NULL,
	[Sold] [int] NULL,
	[Img] [char](256) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Menu]    Script Date: 07/11/2023 10:15:50 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Menu](
	[MenuID] [int] NOT NULL,
	[MenuName] [nvarchar](50) NULL,
	[IsActive] [bit] NULL,
	[ControllerName] [nvarchar](50) NULL,
	[ActionName] [nvarchar](50) NULL,
	[Levels] [int] NULL,
	[ParentID] [int] NULL,
	[Link] [nvarchar](50) NULL,
	[MenuOrder] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 07/11/2023 10:15:50 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[ID] [int] NULL,
	[Name] [nvarchar](100) NULL,
	[username] [char](30) NULL,
	[Phone] [nchar](11) NULL,
	[Mail] [char](30) NULL,
	[Password] [char](30) NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [DB_WebACC] SET  READ_WRITE 
GO
